Term4 - NodeJS - Lab3
Knoddleboy/FICT2 pull request #2
Opened 2023-03-29 19:04 UTC by Knoddleboy

2023-03-29 21:05 UTC, ipiwebtech requested changes
перші три задачі ок, 
4 задачу треба чуть підправити:
давайте в умові 4 задачі обмежимо вхідні значення числами, щоб не використовувати any

2023-03-29 21:14 UTC, Knoddleboy commented
> перші три задачі ок, 4 задачу треба чуть підправити: давайте в умові 4 задачі обмежимо вхідні значення числами, щоб не використовувати any

any -> number

2023-04-11 17:15 UTC, Knoddleboy commented
> перші три задачі ок, 4 задачу треба чуть підправити: давайте в умові 4 задачі обмежимо вхідні значення числами, щоб не використовувати any

Можна мержити?

2023-04-13 15:34 UTC, ipiwebtech approved these changes
ок

чекайте наступну лабку, скоро зроблю

2023-04-13 15:35 UTC, merged