Term4 - NodeJS - Lab5
Knoddleboy/FICT2 pull request #4
Opened 2023-04-19 23:15 UTC by Knoddleboy

2023-05-05 21:00 UTC, nosovk commented on 4term/nodejs/lab5/src/app.ts
> +    if (!username) {
no check for name?

2023-05-05 21:00 UTC, nosovk commented on 4term/nodejs/lab5/src/app.ts
> +        res.status(400).send("Username is required");
json api should return json responce

2023-05-05 21:05 UTC, nosovk commented on 4term/nodejs/lab5/src/app.ts
> +    const { username, name } = req.body;
validate username, name and their type?

2023-05-05 21:07 UTC, nosovk requested changes
add type checks

2023-05-06 11:58 UTC, Knoddleboy commented on 4term/nodejs/lab5/src/app.ts
> +    if (!username) {
`name` is optional

> зробіть ендпоінт "створення користувача" з бов'язковим параметром username і необов'язковим параметром name;

2023-05-10 21:43 UTC, nosovk commented on 4term/nodejs/lab5/package.json
> +    "main": "src/app.ts",
Add "type": "module" to your package.json.
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

2023-05-10 21:45 UTC, nosovk commented on 4term/nodejs/lab5/src/userDb.ts
> +        const id = this.users.length;
this is not ok. If you will delete one entry and then add new user you will get duplicated id's

2023-05-10 21:45 UTC, nosovk commented on 4term/nodejs/lab5/tsconfig.json
> +        "target": "es2016" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
2023.05.10
probably time to update?

2023-05-10 21:46 UTC, nosovk requested changes
fix issues

2023-11-14 18:24 UTC, closed without merging